// Code generated by "stringer -type=Direction -trimprefix=Dir"; DO NOT EDIT.

package pathing

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DirRight-0]
	_ = x[DirDown-1]
	_ = x[DirLeft-2]
	_ = x[DirUp-3]
	_ = x[DirNone-4]
}

const _Direction_name = "RightDownLeftUpNone"

var _Direction_index = [...]uint8{0, 5, 9, 13, 15, 19}

func (i Direction) String() string {
	if i < 0 || i >= Direction(len(_Direction_index)-1) {
		return "Direction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Direction_name[_Direction_index[i]:_Direction_index[i+1]]
}
