// Code generated by "stringer -type=creepKind -trimprefix=creep"; DO NOT EDIT.

package staging

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[creepPrimitiveWanderer-0]
	_ = x[creepStunner-1]
	_ = x[creepAssault-2]
	_ = x[creepDominator-3]
	_ = x[creepBuilder-4]
	_ = x[creepTurret-5]
	_ = x[creepTurretConstruction-6]
	_ = x[creepCrawlerBaseConstruction-7]
	_ = x[creepBase-8]
	_ = x[creepCrawlerBase-9]
	_ = x[creepCrawler-10]
	_ = x[creepHowitzer-11]
	_ = x[creepServant-12]
	_ = x[creepUberBoss-13]
}

const _creepKind_name = "PrimitiveWandererStunnerAssaultDominatorBuilderTurretTurretConstructionCrawlerBaseConstructionBaseCrawlerBaseCrawlerHowitzerServantUberBoss"

var _creepKind_index = [...]uint8{0, 17, 24, 31, 40, 47, 53, 71, 94, 98, 109, 116, 124, 131, 139}

func (i creepKind) String() string {
	if i < 0 || i >= creepKind(len(_creepKind_index)-1) {
		return "creepKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _creepKind_name[_creepKind_index[i]:_creepKind_index[i+1]]
}
