// Code generated by "stringer -type=specialChoiceKind -trimprefix=special"; DO NOT EDIT.

package staging

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[specialChoiceNone-0]
	_ = x[specialIncreaseRadius-1]
	_ = x[specialDecreaseRadius-2]
	_ = x[specialBuildGunpoint-3]
	_ = x[specialBuildColony-4]
	_ = x[specialAttack-5]
	_ = x[specialChoiceMoveColony-6]
	_ = x[specialSendCreeps-7]
	_ = x[specialRally-8]
	_ = x[specialSpawnCrawlers-9]
	_ = x[specialBossAttack-10]
	_ = x[specialIncreaseTech-11]
	_ = x[specialIncreaseTechX2-12]
	_ = x[specialAtomicBomb-13]
	_ = x[specialSendCenturions-14]
	_ = x[_creepCardFirst-15]
	_ = x[specialBuyCrawlers-16]
	_ = x[specialBuyWanderers-17]
	_ = x[specialBuyEliteCrawlers-18]
	_ = x[specialBuyStunners-19]
	_ = x[specialBuyStealthCrawlers-20]
	_ = x[specialBuyHeavyCrawlers-21]
	_ = x[specialBuyBuilders-22]
	_ = x[specialBuyCenturions-23]
	_ = x[specialBuyTemplars-24]
	_ = x[specialBuyAssaults-25]
	_ = x[specialBuyDominator-26]
	_ = x[specialBuyHowitzer-27]
	_ = x[_creepCardLast-28]
}

const _specialChoiceKind_name = "ChoiceNoneIncreaseRadiusDecreaseRadiusBuildGunpointBuildColonyAttackChoiceMoveColonySendCreepsRallySpawnCrawlersBossAttackIncreaseTechIncreaseTechX2AtomicBombSendCenturions_creepCardFirstBuyCrawlersBuyWanderersBuyEliteCrawlersBuyStunnersBuyStealthCrawlersBuyHeavyCrawlersBuyBuildersBuyCenturionsBuyTemplarsBuyAssaultsBuyDominatorBuyHowitzer_creepCardLast"

var _specialChoiceKind_index = [...]uint16{0, 10, 24, 38, 51, 62, 68, 84, 94, 99, 112, 122, 134, 148, 158, 172, 187, 198, 210, 226, 237, 255, 271, 282, 295, 306, 317, 329, 340, 354}

func (i specialChoiceKind) String() string {
	if i < 0 || i >= specialChoiceKind(len(_specialChoiceKind_index)-1) {
		return "specialChoiceKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _specialChoiceKind_name[_specialChoiceKind_index[i]:_specialChoiceKind_index[i+1]]
}
