// Code generated by "stringer -type=specialChoiceKind -trimprefix=special"; DO NOT EDIT.

package staging

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[specialChoiceNone-0]
	_ = x[specialIncreaseRadius-1]
	_ = x[specialDecreaseRadius-2]
	_ = x[specialBuildGunpoint-3]
	_ = x[specialBuildColony-4]
	_ = x[specialAttack-5]
	_ = x[specialChoiceMoveColony-6]
	_ = x[specialSendCreeps-7]
	_ = x[specialRally-8]
	_ = x[specialSpawnCrawlers-9]
	_ = x[specialBossAttack-10]
	_ = x[specialIncreaseTech-11]
	_ = x[specialAtomicBomb-12]
	_ = x[_creepCardFirst-13]
	_ = x[specialBuyCrawlers-14]
	_ = x[specialBuyWanderers-15]
	_ = x[specialBuyEliteCrawlers-16]
	_ = x[specialBuyStunners-17]
	_ = x[specialBuyStealthCrawlers-18]
	_ = x[specialBuyHeavyCrawlers-19]
	_ = x[specialBuyBuilders-20]
	_ = x[specialBuyTemplars-21]
	_ = x[specialBuyAssaults-22]
	_ = x[specialBuyDominator-23]
	_ = x[specialBuyHowitzer-24]
	_ = x[_creepCardLast-25]
}

const _specialChoiceKind_name = "ChoiceNoneIncreaseRadiusDecreaseRadiusBuildGunpointBuildColonyAttackChoiceMoveColonySendCreepsRallySpawnCrawlersBossAttackIncreaseTechAtomicBomb_creepCardFirstBuyCrawlersBuyWanderersBuyEliteCrawlersBuyStunnersBuyStealthCrawlersBuyHeavyCrawlersBuyBuildersBuyTemplarsBuyAssaultsBuyDominatorBuyHowitzer_creepCardLast"

var _specialChoiceKind_index = [...]uint16{0, 10, 24, 38, 51, 62, 68, 84, 94, 99, 112, 122, 134, 144, 159, 170, 182, 198, 209, 227, 243, 254, 265, 276, 288, 299, 313}

func (i specialChoiceKind) String() string {
	if i < 0 || i >= specialChoiceKind(len(_specialChoiceKind_index)-1) {
		return "specialChoiceKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _specialChoiceKind_name[_specialChoiceKind_index[i]:_specialChoiceKind_index[i+1]]
}
