// Code generated by "stringer -type=ColonyAgentKind -trimprefix=Agent"; DO NOT EDIT.

package gamedata

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AgentWorker-0]
	_ = x[AgentMilitia-1]
	_ = x[AgentFreighter-2]
	_ = x[AgentRedminer-3]
	_ = x[AgentCrippler-4]
	_ = x[AgentFighter-5]
	_ = x[AgentPrism-6]
	_ = x[AgentServo-7]
	_ = x[AgentRepeller-8]
	_ = x[AgentRepair-9]
	_ = x[AgentRecharger-10]
	_ = x[AgentGenerator-11]
	_ = x[AgentMortar-12]
	_ = x[AgentAntiAir-13]
	_ = x[AgentRefresher-14]
	_ = x[AgentFlamer-15]
	_ = x[AgentDestroyer-16]
	_ = x[AgentKindNum-17]
	_ = x[AgentGunpoint-18]
}

const _ColonyAgentKind_name = "WorkerMilitiaFreighterRedminerCripplerFighterPrismServoRepellerRepairRechargerGeneratorMortarAntiAirRefresherFlamerDestroyerKindNumGunpoint"

var _ColonyAgentKind_index = [...]uint8{0, 6, 13, 22, 30, 38, 45, 50, 55, 63, 69, 78, 87, 93, 100, 109, 115, 124, 131, 139}

func (i ColonyAgentKind) String() string {
	if i >= ColonyAgentKind(len(_ColonyAgentKind_index)-1) {
		return "ColonyAgentKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ColonyAgentKind_name[_ColonyAgentKind_index[i]:_ColonyAgentKind_index[i+1]]
}
