// Code generated by "stringer -type=CreepKind -trimprefix=Creep"; DO NOT EDIT.

package gamedata

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CreepPrimitiveWanderer-0]
	_ = x[CreepStunner-1]
	_ = x[CreepAssault-2]
	_ = x[CreepDominator-3]
	_ = x[CreepBuilder-4]
	_ = x[CreepTurret-5]
	_ = x[CreepTurretConstruction-6]
	_ = x[CreepCrawlerBaseConstruction-7]
	_ = x[CreepBase-8]
	_ = x[CreepCrawlerBase-9]
	_ = x[CreepCrawler-10]
	_ = x[CreepHowitzer-11]
	_ = x[CreepServant-12]
	_ = x[CreepUberBoss-13]
	_ = x[CreepWisp-14]
	_ = x[CreepWispLair-15]
	_ = x[CreepFortress-16]
	_ = x[CreepTemplar-17]
	_ = x[CreepCenturion-18]
	_ = x[CreepGrenadier-19]
}

const _CreepKind_name = "PrimitiveWandererStunnerAssaultDominatorBuilderTurretTurretConstructionCrawlerBaseConstructionBaseCrawlerBaseCrawlerHowitzerServantUberBossWispWispLairFortressTemplarCenturionGrenadier"

var _CreepKind_index = [...]uint8{0, 17, 24, 31, 40, 47, 53, 71, 94, 98, 109, 116, 124, 131, 139, 143, 151, 159, 166, 175, 184}

func (i CreepKind) String() string {
	if i < 0 || i >= CreepKind(len(_CreepKind_index)-1) {
		return "CreepKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CreepKind_name[_CreepKind_index[i]:_CreepKind_index[i+1]]
}
